################################# Default configuration ###################
baseURL = "https://rbarkow.github.io/yester/"
title = "YESTER."
theme = "meghna"
publishDir = "docs"
canonifyURLs = true

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "Platform"
url = "platform"
weight = 1

[[Languages.en.menu.main]]
name = "Process"
url = "protsess"
weight = 2

[[Languages.en.menu.main]]
name = "Clients"
url = "clients"
weight = 3

[[Languages.en.menu.main]]
name = "Team"
url = "team"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 5

[[Languages.en.menu.app]]
name = "Log in"
url = "https://app.yester.eu"
weight = 1

################### Estonian Navigation ########################
[[Languages.ee.menu.main]]
name = "Platform"
url = "platform"
weight = 1

[[Languages.ee.menu.main]]
name = "Protsess"
url = "protsess"
weight = 2

[[Languages.ee.menu.main]]
name = "Kliendid"
url = "clients"
weight = 3

[[Languages.ee.menu.main]]
name = "Tiim"
url = "team"
weight = 4

[[Languages.ee.menu.main]]
name = "Kontakt"
url = "contact"
weight = 5

[[Languages.ee.menu.app]]
name = "Logi Sisse"
url = "https://app.yester.eu"
weight = 1

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# social icons ##########################
[[params.social]]
icon = "ti-tablet"
link = "https://app.yester.eu"

[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/yester-ltd"

[[params.social]]
icon = "ti-email"
link = "mailto:info@yester.eu"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
description = "Yester on platvorm, kus ettevõtted saavad luua ja jooksutada oma igapäevaseid protsesse. Yester on nagu lego, kus saab protsesse kohandada täpselt vastavalt oma ettevõtte vajadustele. Puhkusetaotlusest kliendikaebusteni, töötajate onboardingust kuni seadmete hoolduse registrini, piire ei ole. Mis protsessid on sinul vaja digitaalseks viia?"
title = "Yester - Platvorm sinu ettevõtte protsesside digitaalseks juhtimiseks"
weight = 1
home = "Home"
copyright = "YESTER. &copy; 2022"

################################ Estonian Language ########################
[Languages.ee]
languageName = "EE"
languageCode = "ee-EE"
contentDir = "content/estonian"
description = "Yester on platvorm, kus ettevõtted saavad luua ja jooksutada oma igapäevaseid protsesse. Yester on nagu lego, kus saab protsesse kohandada täpselt vastavalt oma ettevõtte vajadustele. Puhkusetaotlusest kliendikaebusteni, töötajate onboardingust kuni seadmete hoolduse registrini, piire ei ole. Mis protsessid on sinul vaja digitaalseks viia?"
title = "Yester - Platvorm sinu ettevõtte protsesside digitaalseks juhtimiseks"
weight = 2
home = "Home"
copyright = "YESTER. &copy; 2022"

