name = "YESTER"
description = "Hugo YESTER Template"
homepage = "https://yester.eu/"
demosite = "https://yester.eu/"
min_version = "0.58.0"

[author]
  name = "YESTER"
  homepage = "https://yester.eu"
